## -*- encoding: utf-8 -*-
## This file (sageMathCloud.sagetex.sage) was *autogenerated* from sageMathCloud.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('sageMathCloud', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
